name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: debian-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build
        run: |
          dotnet build